### ISSUE TITLE
Only fetches 30 starred repositories

### ISSUE THREAD

**Issue by notDavid** [stroebjo/alfred-github-stars#2]
Hi there, fyi your workflow only fetches the first 30 starred repos, so if you have more than 30 starred repos a lot of them will be missing. The reason is [Pagination](https://developer.github.com/v3/#pagination).

A quick way to at least bump it from 30 to 100 is:
```$starred_url = sprintf('https://api.github.com/users/%s/starred?per_page=100', $username);```
at line 29 https://github.com/stroebjo/alfred-github-stars/blob/master/app.php#L29

**Comment by stroebjo** [comment]
Thanks for the bug report. I actually already have added support for paginated API responses, but I had an ugly bug in it wich led to only the first and last page of the response to be shown in the results…

I pushed a fix for it and added a [release](https://github.com/stroebjo/alfred-github-stars/releases/tag/v2.1). Please check if this fixes it for you? :)

**Comment by notDavid** [comment]
Ah yes I see, indeed it works now thanks for the fix...!

**Comment by luwes** [comment]
seems this is broken again :(

**Comment by stroebjo** [comment]
> seems this is broken again :(

I tested it on my end and it seemed to work. Can you provide some steps to reproduce? Ist there some output in the Alfred Debug View?

**Comment by luwes** [comment]
my bad, I think it might have been a faulty cache. I reset everything and have access to my older stars again! thanks

**Comment by laike9m** [comment]
I'm still facing this issue. Seems old repos are not cached. How do I clear the cache?

**Comment by stroebjo** [comment]
> I'm still facing this issue. Seems old repos are not cached. How do I clear the cache?

You can delete the `cache.json` in `~/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/de.jonathanstroebele.alfred-github-stars/`. Or set the `cache_ttl` in the workflow variables to 0.

**Comment by laike9m** [comment]
Thanks. Clearing the cache works.

**Comment by laike9m** [comment]
It somehow happens again, this time clearing the cache doesn't help. I even deteled the whole workflow data folder.

**Comment by stroebjo** [comment]
> It somehow happens again, this time clearing the cache doesn't help. I even deteled the whole workflow data folder.

GitHub seems to have changed the header for the results pagination from `Link:` to `link:` and I checked case sensitive. So additional pages didn't get recognized by the workflow. I pushed a new release that should fix it: https://github.com/stroebjo/alfred-github-stars/releases/tag/v2.3

**Comment by laike9m** [comment]
Works now. Thanks for the quick fix!
