### ISSUE TITLE
already set username but still raise an error

### ISSUE THREAD

**Issue by beviz** [stroebjo/alfred-github-stars#5]
![image](https://user-images.githubusercontent.com/1106312/169547218-d783432d-b53c-4512-9263-728d2a768eea.png)

> [22:15:54.611] ERROR: GitHub Stars[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.590D15C1-9122-4BA6-9F0C-BF0FF84F5457%3E59C8DE58-556F-41BA-BEA8-1B6ADDDE7C91)] Code 1: {"items":[{"arg":"https:\/\/www.alfredapp.com\/help\/workflows\/advanced\/variables\/","title":"Please set your GitHub username first","subtitle":"Hit enter to open an introduction to variables."}]}

**Comment by stroebjo** [comment]
Thank for reporting, I published [a new release](https://github.com/stroebjo/alfred-github-stars/releases) that should fix this issue.
